**List Comprehension**

In [33]:
print ([x*x for x in range(100)])
print ([x*x for x in range(100) if x % 2==0])


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604]


**Generators**

In [146]:
def generator_func (n):
    count=0
    var="Meow"
    while count < n:
        #yield var: faire une recherche sur comment ça s'utilise
        print(var)
        count+= 1
        var = var + " "+ var
    return(var)
#attribution d'une valeur spécifique à n
print(generator_func(3))


Meow
Meow Meow
Meow Meow Meow Meow
Meow Meow Meow Meow Meow Meow Meow Meow


**NumPy**

In [36]:
import numpy as np
from numpy.random import seed
from numpy.random import randint
seed(1)
#set 2 lists of random numbers
l1 = [randint(10) for i in range(5)] 
l2 = [randint(10) for i in range(5)]
#create a 2 dimensions Numpy array
a = np.array([l1, l2])
print (a)
x, y = a.shape # the dimensions of the table
#Test the conditions every number in the table 
for i in range(x):
    for j in range(y):
        if a[i,j]>0.9: #If the number > 0.9
            a[i,j]= a[i,j]* a[i,j] # replace it with his square
        else:  #If the number < 0.9
            a[i,j]=42 #replace with 42

print (a) #print the table with the square or 42
print ( a[ : , :4]) # print only 4 columns ofv the table

[[5 8 9 5 0]
 [0 1 7 6 9]]
[[25 64 81 25 42]
 [42  1 49 36 81]]
[[25 64 81 25]
 [42  1 49 36]]
